const data = {
    products:[
        {
            _id :'1',
            name:'Nike Slim Shirt',
            category:'Shirts',
            image:'/images/p1.jpg',
            price:120,
            countInStock:10,
            brand:'Nike',
            rating:4.5,
            numReviews:10,
            description:'high quality product',
        },
        {
            _id :'2',
            name:'Addidas Fit Shirt',
            category:'Shirts',
            image:'/images/p2.jpg',
            price:120,
            countInStock:20,
            brand:'Nike',
            rating:4.5,
            numReviews:10,
            description:'high quality product',
        },
        {
            _id :'3',
            name:'Locoste free Shirt',
            category:'Shirts',
            image:'/images/p3.jpg',
            price:120,
            countInStock:0,
            brand:'Nike',
            rating:4.5,
            numReviews:10,
            description:'high quality product',
        },
        {
            _id :'4',
            name:'Nike Slim Pants',
            category:'Pants',
            image:'/images/p4.jpg',
            price: 80,
            countInStock:5,
            brand:'Nike',
            rating:4.5,
            numReviews:10,
            description:'high quality product',
        },
        {
            _id :'5',
            name:'Puma Slim Pant',
            category:'Pants',
            image:'/images/p5.jpg',
            price:75,
            countInStock:10,
            brand:'Puma',
            rating:4.5,
            numReviews:10,
            description:'high quality product',
        },
        {
            _id :'6',
            name:'Addidas Fit Pant',
            category:'Pants',
            image:'/images/p6.jpg',
            price:55,
            countInStock:12,
            brand:'Nike',
            rating:4.5,
            numReviews:15,
            description:'high quality product',
        }
    ]
}

export default data;